(function(){
const get=id=>P.find(p=>p.id===id), set=(id,c,s)=>{const p=get(id);if(!p)return;if(c)p.construction=c;if(s)p.steps=s};
arc=function(cx,cy,r,a1,a2,k='help'){
 let d=a2-a1;while(d>Math.PI)d-=2*Math.PI;while(d<-Math.PI)d+=2*Math.PI;const a=a1+d;
 const p1={x:cx+r*Math.cos(a1),y:cy+r*Math.sin(a1)},p2={x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)},sw=d>=0?1:0;
 return `<path d="M ${p1.x} ${p1.y} A ${r} ${r} 0 0 ${sw} ${p2.x} ${p2.y}" fill="none" stroke="${col[k]||col.help}" stroke-width="3"/>`;
};
function angleArc(V,P,Q,k='help',r=46){return arc(V.x,V.y,r,Math.atan2(P.y-V.y,P.x-V.x),Math.atan2(Q.y-V.y,Q.x-V.x),k)}
function rayThrough(V,P,k='help'){const dx=P.x-V.x,dy=P.y-V.y,L=Math.max(900,4*Math.hypot(dx,dy)),d=Math.hypot(dx,dy)||1;return line(V,{x:V.x+dx/d*L,y:V.y+dy/d*L},k,true)}
const C={
'sq-a':['AB; |AB| = 5 cm','p; A ∈ p; p ⟂ AB','D; D ∈ p; |AD| = 5 cm','q; D ∈ q; q ∥ AB','r; B ∈ r; r ∥ AD','C; C ∈ q ∩ r','ABCD'],
'sq-e':['AC; |AC| = 4 cm','S; S = střed AC','p; S ∈ p; p ⟂ AC','B, D; B,D ∈ p; |SB| = |SD| = 2 cm','ABCD'],
'rec-ab':['AB; |AB| = 7 cm','p; A ∈ p; p ⟂ AB','D; D ∈ p; |AD| = 4 cm','q; D ∈ q; q ∥ AB','r; B ∈ r; r ∥ AD','C; C ∈ q ∩ r','ABCD'],
'rec-ae':['AB; |AB| = 2,6 cm','p; B ∈ p; p ⟂ AB','k; k(A; 7,8 cm)','C; C ∈ p ∩ k','q; C ∈ q; q ∥ AB','r; A ∈ r; r ∥ BC','D; D ∈ q ∩ r','ABCD'],
'par-abalpha':['AB; |AB| = 7 cm','→AX; ∠BAX = 65°','k; k(A; 4,5 cm)','D; D ∈ →AX ∩ k','p; B ∈ p; p ∥ AD','q; D ∈ q; q ∥ AB','C; C ∈ p ∩ q','ABCD'],
'par-abe':['AC; |AC| = 7 cm','k₁; k₁(A; 6 cm)','k₂; k₂(C; 2,5 cm)','B; B ∈ k₁ ∩ k₂','p; A ∈ p; p ∥ BC','q; C ∈ q; q ∥ AB','D; D ∈ p ∩ q','ABCD'],
'par-efw':['AC; |AC| = 4,2 cm','S; S = střed AC','p; S ∈ p; ∠(p, AC) = 110°','k; k(S; 4,8 cm)','B, D; B,D ∈ p ∩ k','ABCD'],
'rho-aalpha':['AB; |AB| = 5 cm','→AX; ∠BAX = 60°','k; k(A; 5 cm)','D; D ∈ →AX ∩ k','p; B ∈ p; p ∥ AD','q; D ∈ q; q ∥ AB','C; C ∈ p ∩ q','ABCD'],
'rho-ef':['AC; |AC| = 8 cm','S; S = střed AC','p; S ∈ p; p ⟂ AC','k; k(S; 3 cm)','B, D; B,D ∈ p ∩ k','ABCD'],
'rho-ae':['AC; |AC| = 7 cm','k₁; k₁(A; 4 cm)','k₂; k₂(C; 4 cm)','B, D; B,D ∈ k₁ ∩ k₂','ABCD'],
'trap-abcd':['AB; |AB| = 8 cm','E; E ∈ AB; |EB| = 4,7 cm','k₁; k₁(A; 4 cm)','k₂; k₂(E; 2,8 cm)','D; D ∈ k₁ ∩ k₂','p; D ∈ p; p ∥ AB','k₃; k₃(D; 4,7 cm)','C; C ∈ p ∩ k₃','ABCD'],
'trap-acba':['AB; |AB| = 9 cm','E; E ∈ AB; |EB| = 5 cm','→AX; ∠BAX = 60°','k; k(E; 4,5 cm)','D; D ∈ →AX ∩ k','p; D ∈ p; p ∥ AB','k₂; k₂(D; 5 cm)','C; C ∈ p ∩ k₂','ABCD'],
'trap-acvb':['AB; |AB| = 9 cm','p; p ∥ AB; d(p, AB) = 3,5 cm','k; k(B; 4,5 cm)','C; C ∈ p ∩ k','k₂; k₂(C; 5 cm)','D; D ∈ p ∩ k₂','ABCD'],
'rtrap-acv':['AB; |AB| = 9 cm','p; A ∈ p; p ⟂ AB','D; D ∈ p; |AD| = 4 cm','q; D ∈ q; q ∥ AB','k; k(D; 5 cm)','C; C ∈ q ∩ k','ABCD'],
'itrap-acb':['AB; |AB| = 10 cm','X; X ∈ AB; |AX| = 2 cm','p; X ∈ p; p ⟂ AB','k; k(A; 5 cm)','D; D ∈ p ∩ k','q; D ∈ q; q ∥ AB','k₂; k₂(D; 6 cm)','C; C ∈ q ∩ k₂','ABCD'],
'itrap-acv':['AB; |AB| = 10 cm','S; S = střed AB','o; S ∈ o; o ⟂ AB','T; T ∈ o; d(T, AB) = 4 cm','p; T ∈ p; p ∥ AB','k; k(T; 3 cm)','D, C; D,C ∈ p ∩ k','ABCD'],
'itrap-abalpha':['AB; |AB| = 10 cm','→AX; ∠BAX = 60°','k₁; k₁(A; 5 cm)','D; D ∈ →AX ∩ k₁','→BY; ∠ABY = 60°','k₂; k₂(B; 5 cm)','C; C ∈ →BY ∩ k₂','CD','ABCD'],
'kite-abe':['AC; |AC| = 6 cm','k₁; k₁(A; 5 cm)','k₂; k₂(C; 4 cm)','B, D; B,D ∈ k₁ ∩ k₂','ABCD'],
'kite-abf':['BD; |BD| = 6 cm','S; S = střed BD','p; S ∈ p; p ⟂ BD','k₁; k₁(B; 5 cm)','A; A ∈ p ∩ k₁','k₂; k₂(B; 4 cm)','C; C ∈ p ∩ k₂; C je na opačné straně BD než A','ABCD'],
'quad-4se':['AC; |AC| = 7 cm','k₁; k₁(A; 5 cm)','k₂; k₂(C; 4 cm)','B; B ∈ k₁ ∩ k₂','k₃; k₃(A; 5,5 cm)','k₄; k₄(C; 6 cm)','D; D ∈ k₃ ∩ k₄; D je na opačné straně AC než B','ABCD'],
'quad-3s2d':['AC; |AC| = 7 cm','k₁; k₁(A; 5 cm)','k₂; k₂(C; 4 cm)','B; B ∈ k₁ ∩ k₂','k₃; k₃(B; 6 cm)','k₄; k₄(C; 5 cm)','D; D ∈ k₃ ∩ k₄','ABCD'],
'cyclic-Rabc':['k; k(O; 5 cm)','A; A ∈ k','k₁; k₁(A; 6 cm)','B; B ∈ k ∩ k₁','k₂; k₂(B; 5 cm)','C; C ∈ k ∩ k₂; C ≠ A','k₃; k₃(C; 4 cm)','D; D ∈ k ∩ k₃; D ≠ B','ABCD'],
'par-ave':['AB; |AB| = 4,5 cm','p; p ∥ AB; d(p, AB) = 2 cm','k; k(A; 3 cm)','C; C ∈ p ∩ k','q; A ∈ q; q ∥ BC','r; C ∈ r; r ∥ AB','D; D ∈ q ∩ r','ABCD'],
'rec-ew':['S','p; S ∈ p','q; S ∈ q; ∠(p,q) = 120°','k; k(S; 3 cm)','A, C; A,C ∈ p ∩ k','B, D; B,D ∈ q ∩ k','ABCD'],
'par-aef':['AB; |AB| = 4 cm','k₁; k₁(A; 4 cm)','k₂; k₂(B; 3,5 cm)','S; S ∈ k₁ ∩ k₂','C; S = střed AC','D; S = střed BD','ABCD'],
'rho-ev':['XY; |XY| = 4 cm','t; t je Thaletova kružnice nad XY','k; k(Y; 3,7 cm)','Z; Z ∈ t ∩ k','θ = ∠YXZ ≐ 67,7°','AC; |AC| = 4 cm','→AX; ∠XAC ≐ 67,7°','→AY; ∠CAY ≐ 67,7°','p; C ∈ p; p ∥ AY','q; C ∈ q; q ∥ AX','B; B ∈ →AX ∩ p','D; D ∈ →AY ∩ q','ABCD'],
'quad-4sf':['BD; |BD| = 3,8 cm','k₁; k₁(B; 4,7 cm)','k₂; k₂(D; 3,6 cm)','A; A ∈ k₁ ∩ k₂','k₃; k₃(B; 2,4 cm)','k₄; k₄(D; 4,6 cm)','C; C ∈ k₃ ∩ k₄; C je na opačné straně BD než A','ABCD'],
'quad-abcag':['BC; |BC| = 5 cm','→CX; ∠BCX = 78°','k₁; k₁(C; 7,5 cm)','D; D ∈ →CX ∩ k₁','k₂; k₂(B; 6 cm)','t; t je Thaletova kružnice nad BD','A; A ∈ k₂ ∩ t','ABCD'],
'quad-acdeef':['AC; |AC| = 6,7 cm','k₁; k₁(A; 2 cm)','k₂; k₂(C; 5 cm)','D; D ∈ k₁ ∩ k₂','k₃; k₃(A; 7,6 cm)','k₄; k₄(D; 7 cm)','B; B ∈ k₃ ∩ k₄','ABCD'],
'quad-bcdgd':['CD; |CD| = 7 cm','→CX; ∠DCX = 120°','k₁; k₁(C; 3 cm)','B; B ∈ →CX ∩ k₁','→DY; ∠CDY = 38°','k₂; k₂(D; 8,2 cm)','A; A ∈ →DY ∩ k₂','ABCD'],
'quad-mnop':['MP; |MP| = 6 cm','→PX; ∠XPM = 95°','k; k(P; 4 cm)','O; O ∈ →PX ∩ k','→MY; ∠PMY = 45°','→OZ; ∠POZ = 66°','N; N ∈ →MY ∩ →OZ','MNOP'],
'quad-adeg-dac':['AC; |AC| = 7 cm','→AX; ∠XAC = 60°','k₁; k₁(A; 4 cm)','D; D ∈ →AX ∩ k₁','→CY; ∠YCD = 59°','k₂; k₂(A; 3,6 cm)','B; B ∈ →CY ∩ k₂','ABCD'],
'quad-rightv':['UX; |UX| = 8 cm','k₁; k₁(U; 6,5 cm)','k₂; k₂(X; 2 cm)','T; T ∈ k₁ ∩ k₂','t; t je Thaletova kružnice nad UX','k₃; k₃(T; 4 cm)','V; V ∈ t ∩ k₃','TUVX'],
'quad-de-angles-f':['AC; |AC| = 7,5 cm','→AX; ∠XAC = 35°','k₁; k₁(A; 6,5 cm)','D; D ∈ →AX ∩ k₁','→AY; ∠CAY = 23°','k₂; k₂(D; 6 cm)','B; B ∈ →AY ∩ k₂','ABCD'],
'trap-aad-e':['AB; |AB| = 6 cm','→AX; ∠BAX = 52°','k₁; k₁(A; 4 cm)','D; D ∈ →AX ∩ k₁','p; D ∈ p; p ∥ AB','k₂; k₂(A; 5,7 cm)','C; C ∈ p ∩ k₂','BC','ABCD'],
'rtrap-efehfh':['EF; |EF| = 7,3 cm','k₁; k₁(E; 2,5 cm)','k₂; k₂(F; 6,8 cm)','H; H ∈ k₁ ∩ k₂','p; H ∈ p; p ∥ EF','q; F ∈ q; q ⟂ EF','G; G ∈ p ∩ q','EFGH'],
'trap-acvdelta':['AB; |AB| = 4,8 cm','p; p ∥ AB; d(p, AB) = 3,2 cm','α = 180° − 106° = 74°','→AX; ∠BAX = 74°','D; D ∈ →AX ∩ p','k; k(D; 1,8 cm)','C; C ∈ p ∩ k','ABCD'],
'trap-cvef':['CD; |CD| = 7,5 cm','p; p ∥ CD; d(p, CD) = 4 cm','k₁; k₁(C; 4,8 cm)','A; A ∈ p ∩ k₁','k₂; k₂(D; 7,8 cm)','B; B ∈ p ∩ k₂','ABCD'],
'itrap-adbeta':['AB; |AB| = 4,6 cm','→AX; ∠BAX = 70°','k₁; k₁(A; 6 cm)','D; D ∈ →AX ∩ k₁','→BY; ∠ABY = 70°','k₂; k₂(B; 6 cm)','C; C ∈ →BY ∩ k₂','CD','ABCD'],
'itrap-acbeta':['AB; |AB| = 4,6 cm','X; X ∈ AB; |AX| = 0,3 cm','→AY; ∠BAY = 72°','p; X ∈ p; p ⟂ AB','D; D ∈ →AY ∩ p','q; D ∈ q; q ∥ AB','k; k(D; 4 cm)','C; C ∈ q ∩ k','ABCD']
};
for(const [id,c] of Object.entries(C)){const p=get(id);if(p)p.construction=c;}
set('par-abalpha',null,[['Strana','Narýsuj |AB| = 7 cm.'],['Úhel','V A sestroj polopřímku AX, ∠BAX = 65°.'],['Kružnice','Narýsuj k(A; 4,5 cm).'],['Vrchol D','D = →AX ∩ k.'],['Rovnoběžky','Přes B veď rovnoběžku s AD a přes D rovnoběžku s AB.'],['Vrchol C','C je průsečík rovnoběžek.']]);
set('rho-aalpha',null,[['Strana','Narýsuj |AB| = 5 cm.'],['Úhel','V A sestroj polopřímku AX, ∠BAX = 60°.'],['Kružnice','Narýsuj k(A; 5 cm).'],['Vrchol D','D = →AX ∩ k.'],['Rovnoběžky','Přes B a D sestroj příslušné rovnoběžky.'],['Vrchol C','C je jejich průsečík.']]);
set('trap-acba',null,[['Základna','Narýsuj |AB| = 9 cm.'],['Pomocný bod E','Na AB sestroj E tak, aby |EB| = 5 cm.'],['Úhel','V A sestroj polopřímku AX, ∠BAX = 60°.'],['Kružnice','Narýsuj k(E; 4,5 cm).'],['Vrchol D','D = →AX ∩ k.'],['Horní základna','Přes D veď rovnoběžku s AB a pomocí kružnice k₂(D; 5 cm) sestroj C.']]);
set('itrap-abalpha',null,[['Základna','Narýsuj |AB| = 10 cm.'],['Úhel u A','Sestroj →AX, ∠BAX = 60°.'],['Vrchol D','Narýsuj k₁(A; 5 cm); D = →AX ∩ k₁.'],['Úhel u B','Sestroj →BY, ∠ABY = 60°.'],['Vrchol C','Narýsuj k₂(B; 5 cm); C = →BY ∩ k₂.'],['Dokonči','Spoj C a D.']]);
set('quad-bcdgd',null,[['Strana','Narýsuj |CD| = 7 cm.'],['Úhel γ','V C sestroj →CX, ∠DCX = 120°.'],['Vrchol B','Narýsuj k₁(C; 3 cm); B = →CX ∩ k₁.'],['Úhel δ','V D sestroj →DY, ∠CDY = 38°.'],['Vrchol A','Narýsuj k₂(D; 8,2 cm); A = →DY ∩ k₂.'],['Dokonči','Spoj A a B.']]);
set('quad-mnop',null,[['Strana','Narýsuj |MP| = 6 cm.'],['Úhel v P','Sestroj →PX, ∠XPM = 95°.'],['Vrchol O','Narýsuj k(P; 4 cm); O = →PX ∩ k.'],['Úhel v M','Sestroj →MY, ∠PMY = 45°.'],['Úhel v O','Sestroj →OZ, ∠POZ = 66°.'],['Vrchol N','N = →MY ∩ →OZ.']]);
set('quad-adeg-dac',null,[['Úhlopříčka','Narýsuj |AC| = 7 cm.'],['Úhel v A','Sestroj →AX, ∠XAC = 60°.'],['Vrchol D','Narýsuj k₁(A; 4 cm); D = →AX ∩ k₁.'],['Úhel v C','Sestroj →CY, ∠YCD = 59°.'],['Vrchol B','Narýsuj k₂(A; 3,6 cm); B = →CY ∩ k₂.'],['Dokonči','Spoj vrcholy.']]);
set('quad-de-angles-f',null,[['Úhlopříčka','Narýsuj |AC| = 7,5 cm.'],['Úhel DAC','Sestroj →AX, ∠XAC = 35°.'],['Vrchol D','Narýsuj k₁(A; 6,5 cm); D = →AX ∩ k₁.'],['Úhel CAB','Sestroj →AY, ∠CAY = 23°.'],['Vrchol B','Narýsuj k₂(D; 6 cm); B = →AY ∩ k₂.'],['Dokonči','Spoj vrcholy.']]);
set('trap-aad-e',null,[['Základna','Narýsuj |AB| = 6 cm.'],['Úhel','Sestroj →AX, ∠BAX = 52°.'],['Vrchol D','Narýsuj k₁(A; 4 cm); D = →AX ∩ k₁.'],['Rovnoběžka','Přes D veď p ∥ AB.'],['Vrchol C','Narýsuj k₂(A; 5,7 cm); C = p ∩ k₂.'],['Dokonči','Spoj B a C.']]);
set('itrap-adbeta',null,[['Základna','Narýsuj |AB| = 4,6 cm.'],['Úhel u A','Sestroj →AX, ∠BAX = 70°.'],['Vrchol D','Narýsuj k₁(A; 6 cm); D = →AX ∩ k₁.'],['Úhel u B','Sestroj →BY, ∠ABY = 70°.'],['Vrchol C','Narýsuj k₂(B; 6 cm); C = →BY ∩ k₂.'],['Dokonči','Spoj C a D.']]);
set('quad-abcag',null,[['Strana b','Narýsuj |BC| = 5 cm.'],['Úhel γ','V C sestroj polopřímku CX, ∠BCX = 78°.'],['Vrchol D','Narýsuj k₁(C; 7,5 cm); D = →CX ∩ k₁.'],['Strana a','Narýsuj k₂(B; 6 cm).'],['Pravý úhel α','Nad BD sestroj Thaletovu kružnici t.'],['Vrchol A','A = k₂ ∩ t.']]);
set('rec-ew',null,[['Střed','Zvol bod S.'],['Směry úhlopříček','Sestroj přímky p a q bodem S tak, aby ∠(p,q) = 120°.'],['Kružnice','Narýsuj k(S; 3 cm).'],['Vrchol A a C','A a C jsou průsečíky k s p.'],['Vrchol B a D','B a D jsou průsečíky k s q.'],['Dokonči','Spoj A–B–C–D–A.']]);
set('trap-acvdelta',null,[['Základna','Narýsuj |AB| = 4,8 cm.'],['Výška','Sestroj p ∥ AB ve vzdálenosti 3,2 cm.'],['Dopočet úhlu','α = 180° − 106° = 74°.'],['Polopřímka','V A sestroj →AX, ∠BAX = 74°.'],['Vrchol D','D = →AX ∩ p.'],['Vrchol C','Narýsuj k(D; 1,8 cm); C = p ∩ k.']]);
set('itrap-acbeta',null,[['Základna','Narýsuj |AB| = 4,6 cm.'],['Pomocný bod','Na AB sestroj X, |AX| = 0,3 cm.'],['Úhel','V A sestroj →AY, ∠BAY = 72°.'],['Kolmice','V X sestroj p ⟂ AB.'],['Vrchol D','D = →AY ∩ p.'],['Horní základna','Přes D veď q ∥ AB a narýsuj k(D; 4 cm).'],['Vrchol C','C = q ∩ k.']]);
const oldDraw=draw,A={};
function ed(q,k='final'){return [line(q.A,q.B,k),line(q.B,q.C,k),line(q.C,q.D,k),line(q.D,q.A,k)]}
A['par-abalpha']=A['rho-aalpha']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),r=Math.hypot(q.D.x-q.A.x,q.D.y-q.A.y),z=[line(q.A,q.B,'base'),pt(q.A,'A'),pt(q.B,'B')];if(s>=1)z.push(rayThrough(q.A,q.D),angleArc(q.A,q.B,q.D));if(s>=2)z.push(circ(q.A,r,'help',true));if(s>=3)z.push(pt(q.D,'D','final'));if(s>=4)z.push(line(q.B,q.C,'help',true),line(q.D,q.C,'help',true));if(s>=5)z.push(pt(q.C,'C','final'),...ed(q));return svg(z)};
A['trap-acba']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),E={x:q.B.x-(q.C.x-q.D.x),y:q.B.y},z=[line(q.A,q.B,'base'),pt(q.A,'A'),pt(q.B,'B')];if(s>=1)z.push(pt(E,'E'));if(s>=2)z.push(rayThrough(q.A,q.D),angleArc(q.A,q.B,q.D));if(s>=3)z.push(circ(E,Math.hypot(q.D.x-E.x,q.D.y-E.y),'help',true));if(s>=4)z.push(pt(q.D,'D','final'));if(s>=5)z.push(line(q.D,q.C,'help',true),circ(q.D,Math.hypot(q.C.x-q.D.x,q.C.y-q.D.y),'help',true),pt(q.C,'C','final'),...ed(q));return svg(z)};
A['itrap-abalpha']=A['itrap-adbeta']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),z=[line(q.A,q.B,'base'),pt(q.A,'A'),pt(q.B,'B')];if(s>=1)z.push(rayThrough(q.A,q.D),angleArc(q.A,q.B,q.D));if(s>=2)z.push(circ(q.A,Math.hypot(q.A.x-q.D.x,q.A.y-q.D.y),'help',true),pt(q.D,'D','final'));if(s>=3)z.push(rayThrough(q.B,q.C),angleArc(q.B,q.A,q.C));if(s>=4)z.push(circ(q.B,Math.hypot(q.B.x-q.C.x,q.B.y-q.C.y),'help',true),pt(q.C,'C','final'));if(s>=5)z.push(...ed(q));return svg(z)};
A['par-efw']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),S={x:(q.A.x+q.C.x)/2,y:(q.A.y+q.C.y)/2},z=[line(q.A,q.C,'base'),pt(q.A,'A'),pt(q.C,'C')];if(s>=1)z.push(pt(S,'S'));if(s>=2)z.push(line(q.B,q.D,'help',true),angleArc(S,q.A,q.B));if(s>=3)z.push(circ(S,Math.hypot(q.B.x-S.x,q.B.y-S.y),'help',true));if(s>=4)z.push(pt(q.B,'B','final'),pt(q.D,'D','final'),...ed(q));return svg(z)};
A['quad-bcdgd']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),z=[line(q.C,q.D,'base'),pt(q.C,'C'),pt(q.D,'D')];if(s>=1)z.push(rayThrough(q.C,q.B),angleArc(q.C,q.D,q.B));if(s>=2)z.push(circ(q.C,Math.hypot(q.B.x-q.C.x,q.B.y-q.C.y),'help',true),pt(q.B,'B','final'));if(s>=3)z.push(rayThrough(q.D,q.A),angleArc(q.D,q.C,q.A));if(s>=4)z.push(circ(q.D,Math.hypot(q.A.x-q.D.x,q.A.y-q.D.y),'help',true),pt(q.A,'A','final'));if(s>=5)z.push(...ed(q));return svg(z)};
A['quad-mnop']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),z=[line(q.A,q.D,'base'),pt(q.A,'M'),pt(q.D,'P')];if(s>=1)z.push(rayThrough(q.D,q.C),angleArc(q.D,q.A,q.C));if(s>=2)z.push(circ(q.D,Math.hypot(q.C.x-q.D.x,q.C.y-q.D.y),'help',true),pt(q.C,'O','final'));if(s>=3)z.push(rayThrough(q.A,q.B),angleArc(q.A,q.D,q.B));if(s>=4)z.push(rayThrough(q.C,q.B),angleArc(q.C,q.D,q.B));if(s>=5)z.push(pt(q.B,'N','final'),...ed(q));return svg(z)};
A['quad-adeg-dac']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),z=[line(q.A,q.C,'base'),pt(q.A,'A'),pt(q.C,'C')];if(s>=1)z.push(rayThrough(q.A,q.D),angleArc(q.A,q.C,q.D));if(s>=2)z.push(circ(q.A,Math.hypot(q.D.x-q.A.x,q.D.y-q.A.y),'help',true),pt(q.D,'D','final'));if(s>=3)z.push(rayThrough(q.C,q.B),angleArc(q.C,q.D,q.B));if(s>=4)z.push(circ(q.A,Math.hypot(q.B.x-q.A.x,q.B.y-q.A.y),'help',true),pt(q.B,'B','final'));if(s>=5)z.push(...ed(q));return svg(z)};
A['quad-de-angles-f']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),z=[line(q.A,q.C,'base'),pt(q.A,'A'),pt(q.C,'C')];if(s>=1)z.push(rayThrough(q.A,q.D),angleArc(q.A,q.C,q.D));if(s>=2)z.push(circ(q.A,Math.hypot(q.D.x-q.A.x,q.D.y-q.A.y),'help',true),pt(q.D,'D','final'));if(s>=3)z.push(rayThrough(q.A,q.B),angleArc(q.A,q.C,q.B));if(s>=4)z.push(circ(q.D,Math.hypot(q.B.x-q.D.x,q.B.y-q.D.y),'help',true),pt(q.B,'B','final'));if(s>=5)z.push(...ed(q));return svg(z)};
A['trap-aad-e']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),z=[line(q.A,q.B,'base'),pt(q.A,'A'),pt(q.B,'B')];if(s>=1)z.push(rayThrough(q.A,q.D),angleArc(q.A,q.B,q.D));if(s>=2)z.push(circ(q.A,Math.hypot(q.D.x-q.A.x,q.D.y-q.A.y),'help',true),pt(q.D,'D','final'));if(s>=3)z.push(line(q.D,q.C,'help',true));if(s>=4)z.push(circ(q.A,Math.hypot(q.C.x-q.A.x,q.C.y-q.A.y),'help',true),pt(q.C,'C','final'));if(s>=5)z.push(...ed(q));return svg(z)};
A['quad-abcag']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),z=[line(q.B,q.C,'base'),pt(q.B,'B'),pt(q.C,'C')];if(s>=1)z.push(rayThrough(q.C,q.D),angleArc(q.C,q.B,q.D));if(s>=2)z.push(circ(q.C,Math.hypot(q.D.x-q.C.x,q.D.y-q.C.y),'help',true),pt(q.D,'D','final'));if(s>=3)z.push(circ(q.B,Math.hypot(q.A.x-q.B.x,q.A.y-q.B.y),'help',true));if(s>=4)z.push(circ({x:(q.B.x+q.D.x)/2,y:(q.B.y+q.D.y)/2},Math.hypot(q.B.x-q.D.x,q.B.y-q.D.y)/2,'help',true));if(s>=5)z.push(pt(q.A,'A','final'),...ed(q));return svg(z)};
A['rec-ew']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),S={x:(q.A.x+q.C.x)/2,y:(q.A.y+q.C.y)/2},r=Math.hypot(q.A.x-S.x,q.A.y-S.y),z=[pt(S,'S')];if(s>=1)z.push(line(q.A,q.C,'help',true),line(q.B,q.D,'help',true),angleArc(S,q.A,q.B));if(s>=2)z.push(circ(S,r,'help',true));if(s>=3)z.push(pt(q.A,'A','final'),pt(q.C,'C','final'));if(s>=4)z.push(pt(q.B,'B','final'),pt(q.D,'D','final'));if(s>=5)z.push(...ed(q));return svg(z)};
A['trap-acvdelta']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),z=[line(q.A,q.B,'base'),pt(q.A,'A'),pt(q.B,'B')];if(s>=1)z.push(line({x:60,y:q.D.y},{x:760,y:q.D.y},'help',true));if(s>=2)z.push(txt(85,100,'α = 74°'));if(s>=3)z.push(rayThrough(q.A,q.D),angleArc(q.A,q.B,q.D));if(s>=4)z.push(pt(q.D,'D','final'));if(s>=5)z.push(circ(q.D,Math.hypot(q.C.x-q.D.x,q.C.y-q.D.y),'help',true),pt(q.C,'C','final'),...ed(q));return svg(z)};
A['itrap-acbeta']=(p,s)=>{prepareGeometry(p);const q=shape(p.diagram),X={x:q.D.x,y:q.A.y},z=[line(q.A,q.B,'base'),pt(q.A,'A'),pt(q.B,'B')];if(s>=1)z.push(pt(X,'X'),line(q.A,X,'help'));if(s>=2)z.push(rayThrough(q.A,q.D),angleArc(q.A,q.B,q.D));if(s>=3)z.push(line({x:X.x,y:520},{x:X.x,y:60},'help',true));if(s>=4)z.push(pt(q.D,'D','final'));if(s>=5)z.push(line(q.D,q.C,'help',true),circ(q.D,Math.hypot(q.C.x-q.D.x,q.C.y-q.D.y),'help',true));if(s>=6)z.push(pt(q.C,'C','final'),...ed(q));return svg(z)};
draw=function(p,s){return A[p.id]?A[p.id](p,s):oldDraw(p,s)};
if(typeof renderAll==='function')renderAll();
})();
