function fmtSegments(s){ return String(s ?? '').replace(/(?<!\|)\b([A-Z]{2})\b(?=\s*=)/g,'|$1|'); }
function czConstructionStep(raw){
 let s=fmtSegments(raw).trim(); if(!s)return s;
 s=s.replace(/\s*=\s*/g,' = ').replace(/\s*∈\s*/g,' ∈ ').replace(/\s*∥\s*/g,' ∥ ').replace(/\s*⟂\s*/g,' ⟂ ').replace(/\s*∩\s*/g,' ∩ ').replace(/\s*;\s*/g,'; ').replace(/\s*,\s*/g,', ').replace(/\s+/g,' ').trim();
 let m=s.match(/^(k(?:[₀-₉0-9]+)?|l(?:[₀-₉0-9]+)?)\(([^)]+)\)$/); if(m)return `${m[1]}; ${m[1]}(${m[2]})`;
 m=s.match(/^([a-z][₀-₉0-9′']*)\s*⟂\s*([A-Z]{2})\s+v\s+([A-Z])(?:;\s*(.*))?$/); if(m)return `${m[1]}; ${m[3]} ∈ ${m[1]}; ${m[1]} ⟂ ${m[2]}${m[4]?`; ${m[4]}`:''}`;
 m=s.match(/^([a-z][₀-₉0-9′']*)\s*∥\s*([A-Z]{2})\s+přes\s+([A-Z])(?:;\s*(.*))?$/); if(m)return `${m[1]}; ${m[3]} ∈ ${m[1]}; ${m[1]} ∥ ${m[2]}${m[4]?`; ${m[4]}`:''}`;
 m=s.match(/^([a-z][₀-₉0-9′']*)\s*∥\s*([A-Z]{2})(?:;\s*(.*))?$/); if(m)return `${m[1]}; ${m[1]} ∥ ${m[2]}${m[3]?`; ${m[3]}`:''}`;
 m=s.match(/^([a-z][₀-₉0-9′']*)\s+přes\s+([A-Z]);\s*(.+)$/i); if(m)return `${m[1]}; ${m[2]} ∈ ${m[1]}; ${m[3]}`;
 m=s.match(/^([A-Z](?:[₀-₉0-9′']*)?(?:,\s*[A-Z](?:[₀-₉0-9′']*)?)?)\s*∈\s*(.+)$/); if(m)return `${m[1]}; ${m[1]} ∈ ${m[2]}`;
 m=s.match(/^([A-Z](?:[₀-₉0-9′']*)?)\s*=\s*střed\s+([A-Z]{2})(?:;\s*(.*))?$/); if(m)return `${m[1]}; ${m[1]} = střed ${m[2]}${m[3]?`; ${m[3]}`:''}`;
 m=s.match(/^([A-Z](?:[₀-₉0-9′']*)?)\s*=\s*(.+∩.+)$/); if(m)return `${m[1]}; ${m[1]} ∈ ${m[2]}`;
 m=s.match(/^([A-Z])\s+obraz\s+([A-Z])\s+podle\s+([A-Z])$/i); if(m)return `${m[1]}; ${m[3]} = střed ${m[1]}${m[2]}`;
 m=s.match(/^oblouk\s+([a-z])\s*:\s*(∠.+)$/i); if(m)return `${m[1]}; ${m[1]} = {X; ${m[2]}}`;
 return s;
}
function czConstructionForProblem(p){
 const special={
  'par-abe':['AC; |AC| = e','k₁; k₁(A; a)','k₂; k₂(C; b)','B; B ∈ k₁ ∩ k₂','p; A ∈ p; p ∥ BC','q; C ∈ q; q ∥ AB','D; D ∈ p ∩ q','ABCD'],
  'par-ave':['AB; |AB| = a','p; p ∥ AB; d(p, AB) = vₐ','k; k(A; e)','C; C ∈ p ∩ k','q; A ∈ q; q ∥ BC','r; C ∈ r; r ∥ AB','D; D ∈ q ∩ r','ABCD'],
  'rho-aalpha':['AB; |AB| = a','→AD; ∠DAB = α','D; D ∈ →AD; |AD| = a','p; B ∈ p; p ∥ AD','q; D ∈ q; q ∥ AB','C; C ∈ p ∩ q','ABCD'],
  'par-aef':['AB; |AB| = a','k₁; k₁(A; e/2)','k₂; k₂(B; f/2)','S; S ∈ k₁ ∩ k₂','C; S = střed AC','D; S = střed BD','ABCD'],
  'rho-ev':['XY; |XY| = e','t; t je Thaletova kružnice nad XY','k; k(Y; v)','Z; Z ∈ t ∩ k','θ; θ = ∠YXZ','AC; |AC| = e','→AB; ∠BAC = θ','→AD; ∠CAD = θ','p; C ∈ p; p ∥ AD','q; C ∈ q; q ∥ AB','B; B ∈ →AB ∩ p','D; D ∈ →AD ∩ q','ABCD'],
  'rec-ew':['S','p, q; S ∈ p; S ∈ q; ∠(p, q) = ω','A, C; A, C ∈ p; |SA| = |SC| = e/2','B, D; B, D ∈ q; |SB| = |SD| = e/2','ABCD']
 };
 return (special[p.id]||p.construction.map(czConstructionStep));
}
function desktopTemplate(p){const cz=czConstructionForProblem(p);return `<div class="grid"><section class="card"><div class="eyebrow">${p.cat}</div><h1>${p.title}</h1><p class="lead">${fmtSegments(p.find)}</p><div class="badges">${p.tags.map(t=>`<span class="badge">${t}</span>`).join('')}</div><dl class="kv"><dt>Zadáno</dt><dd><b>${fmtSegments(p.given)}</b></dd><dt>Úkol</dt><dd>${fmtSegments(p.find)}</dd><dt>Varianty</dt><dd>${fmtSegments(p.variants)}</dd></dl><div class="notice"><b>Podmínka / počet řešení:</b><br>${fmtSegments(p.existence)}</div><div class="construction sketchbox"><h3>Náčrtek situace</h3><div class="sketch-preview">${drawSketch(p)}</div><p><b>Zeleně</b> známé údaje, <b>černě</b> neznámé části a <b>oranžově</b> pomocné prvky.</p><div class="scale-note">Tvar je vykreslen v poměru podle zadaných délek a úhlů; pouze celkové měřítko se přizpůsobí oknu. Délky úseček zapisujeme jako |AB|, |AC| apod.</div></div><button id="solutionToggle" class="solution-toggle">${openSolution?'Skrýt řešení':'Rozbalit kompletní řešení'}</button><div class="solution ${openSolution?'open':''}"><div class="steps">${p.steps.map((s,i)=>`<div class="step ${i===stepIndex?'active':''}" data-step="${i}"><span class="num">${i+1}</span><strong>${fmtSegments(s[0])}</strong><p>${fmtSegments(s[1])}</p></div>`).join('')}</div><div class="construction"><h3>Zápis konstrukce</h3><ol>${cz.map(x=>`<li>${x}</li>`).join('')}</ol><div style="margin-top:10px;padding-top:9px;border-top:1px solid var(--line);color:#64748b;font-size:12.5px;line-height:1.45">Zápis je veden běžným českým školním způsobem: nejprve objekt, za středníkem jeho určující vlastnost; nový bod se zapisuje pomocí příslušnosti nebo průsečíku.</div></div></div></section><section class="card diagram-card"><div class="diagram-head"><span class="diagram-title">Grafické řešení krok po kroku</span><span class="step-counter">Krok ${stepIndex+1} z ${p.steps.length}</span></div><div id="svgWrap">${draw(p,stepIndex)}</div><div class="diagram-controls"><button id="prevStep">← Krok zpět</button><button class="primary" id="nextStep">Další krok →</button></div><div class="legend"><span><i class="l-unknown"></i>základ / neznámé</span><span><i class="l-help"></i>pomocné</span><span><i class="l-known"></i>hotové</span></div></section></div>`}
function accordion(k,icon,title,body){const o=mobilePanels[k];return `<section class="mobile-accordion ${o?'open':''}"><button class="mobile-accordion-toggle" data-toggle="${k}"><span class="left"><span class="icon">${icon}</span><span>${title}</span></span><span class="chev">⌄</span></button><div class="mobile-accordion-panel">${body}</div></section>`}
function mobileTemplate(p){const cz=czConstructionForProblem(p);const sk=`<div>${drawSketch(p)}</div><p class="mobile-sketch-note"><b>Zeleně</b> známé údaje, <b>černě</b> neznámé části a <b>oranžově</b> pomocné prvky. Tvar odpovídá poměrům v zadání.</p>`;const st=`<div class="mobile-procedure-diagram"><div class="diagram-head"><b>Grafický krok</b><span class="step-counter">Krok ${stepIndex+1} z ${p.steps.length}</span></div>${draw(p,stepIndex)}<div class="diagram-controls"><button id="mPrevStep">← Krok zpět</button><button class="primary" id="mNextStep">Další krok →</button></div></div><div class="mobile-steps">${p.steps.map((s,i)=>`<div class="step ${i===stepIndex?'active':''}" data-mstep="${i}"><span class="num">${i+1}</span><strong>${fmtSegments(s[0])}</strong><p>${fmtSegments(s[1])}</p></div>`).join('')}</div>`;const co=`<div class="mobile-construction"><ol>${cz.map(x=>`<li>${x}</li>`).join('')}</ol></div>`;return `<article class="mobile-detail-card"><div class="eyebrow">${p.cat}</div><h1>${p.title}</h1><p class="lead">${fmtSegments(p.find)}</p><div class="badges">${p.tags.map(t=>`<span class="badge">${t}</span>`).join('')}</div><div class="mobile-assignment"><div class="mobile-assignment-row"><span>Zadáno</span><b>${fmtSegments(p.given)}</b></div><div class="mobile-assignment-row"><span>Úkol</span><div>${fmtSegments(p.find)}</div></div><div class="mobile-assignment-row"><span>Varianty</span><div>${fmtSegments(p.variants)}</div></div></div><div class="notice"><b>Podmínka / počet řešení:</b><br>${fmtSegments(p.existence)}</div><div class="mobile-accordions">${accordion('sketch','▱','Náčrtek',sk)}${accordion('steps','1→','Konstrukce krok po kroku',st)}${accordion('construction','✎','Zápis konstrukce',co)}</div></article>`}