P.push(
{id:"sq-a",cat:"Čtverec",title:"Čtverec – strana a",tags:["čtverec","strana"],given:"a = 5 cm",find:"Sestroj čtverec ABCD.",existence:"Pro každé a > 0 existuje právě jeden tvar čtverce.",variants:"Nejzákladnější konstrukce čtverce.",diagram:"squareSide",steps:[["Strana","Narýsuj |AB| = a."],["Kolmice","V A sestroj kolmici k AB."],["Druhá strana","Na kolmici odměř |AD| = a."],["Rovnoběžky","Bodem D veď rovnoběžku s AB a bodem B rovnoběžku s AD."],["Dokonči","Průsečík rovnoběžek je C."]],construction:["AB; |AB|=a","p ⟂ AB v A","D∈p; |AD|=a","q∥AB přes D; r∥AD přes B","C=q∩r","ABCD"]},
{id:"sq-e",cat:"Čtverec",title:"Čtverec – úhlopříčka e",tags:["čtverec","úhlopříčka"],given:"e = 4 cm",find:"Sestroj čtverec ABCD s |AC| = e.",existence:"Úhlopříčky čtverce jsou stejně dlouhé, kolmé a navzájem se půlí.",variants:"Lze samozřejmě zadat i úhlopříčku BD.",diagram:"squareDiag",steps:[["Úhlopříčka","Narýsuj |AC| = e."],["Střed","Sestroj střed S úsečky AC."],["Kolmice","V S sestroj kolmici k AC."],["Druhá úhlopříčka","Na kolmici odměř |SB| = |SD| = e/2."],["Dokonči","Spoj A–B–C–D–A."]],construction:["AC; |AC|=e","S=střed AC","p⟂AC v S","B,D∈p; |SB|=|SD|=e/2","ABCD"]},
{id:"rec-ab",cat:"Obdélník",title:"Obdélník – strany a, b",tags:["obdélník","2 strany"],given:"a = 7 cm, b = 4 cm",find:"Sestroj obdélník ABCD.",existence:"Pro a > 0 a b > 0 existuje právě jeden tvar obdélníku.",variants:"Strany a a b lze zaměnit.",diagram:"rectSides",steps:[["Základna","Narýsuj |AB| = a."],["Kolmice","V A sestroj kolmici k AB."],["Druhá strana","Na kolmici odměř |AD| = b."],["Rovnoběžky","Přes D veď rovnoběžku s AB a přes B rovnoběžku s AD."],["Dokonči","Jejich průsečík je C."]],construction:["AB; |AB|=a","p⟂AB v A","D∈p; |AD|=b","q∥AB přes D; r∥AD přes B","C=q∩r","ABCD"]},
{id:"rec-ae",cat:"Obdélník",title:"Obdélník – strana a a úhlopříčka e",tags:["obdélník","úhlopříčka"],given:"a = 2,6 cm, e = 7,8 cm",find:"Sestroj obdélník ABCD s |AC| = e.",existence:"Musí platit e > a, protože AC je přepona pravoúhlého trojúhelníku ABC.",variants:"Analogicky lze zadat stranu b a úhlopříčku.",diagram:"rectDiag",steps:[["Základna","Narýsuj |AB| = a."],["Kolmice v B","V B sestroj kolmici k AB."],["Kružnice","Narýsuj kružnici k(A; e)."],["Vrchol C","Průsečík kružnice s kolmicí je C."],["Doplň obdélník","Doplň D pomocí rovnoběžek."]],construction:["AB; |AB|=a","p⟂AB v B","k(A;e)","C∈p∩k","q∥AB přes C; r∥BC přes A; D=q∩r","ABCD"]},
{id:"par-abalpha",cat:"Rovnoběžník",title:"Rovnoběžník – dvě strany a úhel",tags:["rovnoběžník","úhel"],given:"a = 7 cm, b = 4,5 cm, α = 65°",find:"Sestroj rovnoběžník ABCD.",existence:"Pro a,b > 0 a 0° < α < 180° vznikne právě jeden tvar.",variants:"Úhel může být kterýkoli vnitřní úhel rovnoběžníku.",diagram:"paraAngle",steps:[["Základna","Narýsuj |AB| = a."],["Úhel","V A sestroj polopřímku AD s ∠DAB = α."],["Druhá strana","Odměř |AD| = b."],["Rovnoběžky","Doplň dvě rovnoběžky."],["Dokonči","Jejich průsečík je C."]],construction:["AB; |AB|=a","∠DAB=α","D∈→AD; |AD|=b","p∥AD přes B; q∥AB přes D","C=p∩q","ABCD"]},
{id:"par-abe",cat:"Rovnoběžník",title:"Rovnoběžník – dvě strany a úhlopříčka e",tags:["rovnoběžník","SSS","úhlopříčka"],given:"a = 6 cm, b = 2,5 cm, e = |AC| = 7 cm",find:"Sestroj rovnoběžník ABCD.",existence:"Nejprve musí existovat trojúhelník ABC se stranami a, b, e.",variants:"Nejprve se řeší trojúhelník ABC podle SSS.",diagram:"paraDiag",steps:[["Úhlopříčka","Narýsuj |AC| = e."],["Kružnice z A","Narýsuj k₁(A; a)."],["Kružnice z C","Narýsuj k₂(C; b)."],["Vrchol B","Průsečík kružnic je B."],["Doplň D","Doplň rovnoběžník pomocí rovnoběžek."]],construction:["AC; |AC|=e","k₁(A;a)","k₂(C;b)","B∈k₁∩k₂","D pomocí rovnoběžek","ABCD"]},
{id:"par-efw",cat:"Rovnoběžník",title:"Rovnoběžník – úhlopříčky e, f a úhel ω",tags:["rovnoběžník","2 úhlopříčky"],given:"e = 4,2 cm, f = 9,6 cm, ω = 110°",find:"Sestroj rovnoběžník ABCD.",existence:"Úhlopříčky rovnoběžníku se navzájem půlí.",variants:"ω je úhel mezi úhlopříčkami AC a BD.",diagram:"paraDiags",steps:[["První úhlopříčka","Narýsuj |AC| = e a najdi její střed S."],["Směr druhé","V S sestroj přímku svírající s AC úhel ω."],["Druhá úhlopříčka","Odměř |SB| = |SD| = f/2."],["Dokonči","Spoj A–B–C–D–A."]],construction:["AC; |AC|=e","S=střed AC","p přes S; ∠(p,AC)=ω","B,D∈p; |SB|=|SD|=f/2","ABCD"]},
{id:"rho-aalpha",cat:"Kosočtverec",title:"Kosočtverec – strana a a úhel α",tags:["kosočtverec","úhel"],given:"a = 5 cm, α = 60°",find:"Sestroj kosočtverec ABCD.",existence:"Kosočtverec je rovnoběžník se všemi stranami stejně dlouhými.",variants:"Postup vychází z konstrukce rovnoběžníku.",diagram:"rhombAngle",steps:[["Strana","Narýsuj |AB| = a."],["Úhel","V A sestroj ∠DAB = α."],["Druhá strana","Odměř |AD| = a."],["Rovnoběžky","Doplň rovnoběžník."],["Dokonči","Zvýrazni kosočtverec."]],construction:["AB; |AB|=a","∠DAB=α","D∈→AD; |AD|=a","rovnoběžky přes B a D","C=jejich průsečík","ABCD"]},
{id:"rho-ef",cat:"Kosočtverec",title:"Kosočtverec – obě úhlopříčky e, f",tags:["kosočtverec","2 úhlopříčky"],given:"e = 8 cm, f = 6 cm",find:"Sestroj kosočtverec ABCD.",existence:"Úhlopříčky kosočtverce jsou kolmé a navzájem se půlí.",variants:"Délky e a f nemusí být stejné.",diagram:"rhombDiags",steps:[["První úhlopříčka","Narýsuj |AC| = e."],["Střed","Najdi střed S."],["Kolmice","V S sestroj kolmici k AC."],["Druhá úhlopříčka","Odměř |SB| = |SD| = f/2."],["Dokonči","Spoj vrcholy."]],construction:["AC; |AC|=e","S=střed AC","p⟂AC v S","B,D∈p; |SB|=|SD|=f/2","ABCD"]},
{id:"rho-ae",cat:"Kosočtverec",title:"Kosočtverec – strana a a úhlopříčka e",tags:["kosočtverec","úhlopříčka"],given:"a = 4 cm, e = |AC| = 7 cm",find:"Sestroj kosočtverec ABCD.",existence:"Musí platit e < 2a.",variants:"Body B a D jsou průsečíky dvou kružnic se stejným poloměrem a.",diagram:"rhombSideDiag",steps:[["Úhlopříčka","Narýsuj |AC| = e."],["Kružnice z A","Narýsuj k₁(A; a)."],["Kružnice z C","Narýsuj k₂(C; a)."],["Vrchol B a D","Průsečíky jsou B a D."],["Dokonči","Spoj vrcholy."]],construction:["AC; |AC|=e","k₁(A;a)","k₂(C;a)","B,D∈k₁∩k₂","ABCD"]}
);
