(function(){
 const bad=typeof P!=='undefined'?P.find(x=>x.id==='a-alpha-ta'):null;
 if(bad&&/tₐ\s*=\s*4,1/.test(bad.given)) bad.given=bad.given.replace(/tₐ\s*=\s*4,1\s*cm/,'tₐ = 3,5 cm');
 const style=document.createElement('style');style.textContent='.scale-note{font-size:12px;color:#64748b;margin-top:6px}.construction-note{margin-top:10px;padding-top:9px;border-top:1px solid var(--line);color:#64748b;font-size:12.5px;line-height:1.45}';document.head.appendChild(style);
 window.fmtSegments=function(s){return String(s??'').replace(/(?<!\|)\b([A-Z]{2})\b(?=\s*=)/g,'|$1|')};
 window.czConstructionStep=function(raw){
  let s=fmtSegments(raw).trim();if(!s)return s;
  s=s.replace(/\s*=\s*/g,' = ').replace(/\s*∈\s*/g,' ∈ ').replace(/\s*∥\s*/g,' ∥ ').replace(/\s*⟂\s*/g,' ⟂ ').replace(/\s*∩\s*/g,' ∩ ').replace(/\s*;\s*/g,'; ').replace(/\s*,\s*/g,', ').replace(/\s+/g,' ').trim();
  let m=s.match(/^(k(?:[₀-₉0-9]+)?|l(?:[₀-₉0-9]+)?)\(([^)]+)\)$/);if(m)return `${m[1]}; ${m[1]}(${m[2]})`;
  m=s.match(/^([a-z][₀-₉0-9′']*)\s*⟂\s*([A-Z]{2})\s+v\s+([A-Z])(?:;\s*(.*))?$/);if(m)return `${m[1]}; ${m[3]} ∈ ${m[1]}; ${m[1]} ⟂ ${m[2]}${m[4]?`; ${m[4]}`:''}`;
  m=s.match(/^([a-z][₀-₉0-9′']*)\s*∥\s*([A-Z]{2})(?:;\s*(.*))?$/);if(m)return `${m[1]}; ${m[1]} ∥ ${m[2]}${m[3]?`; ${m[3]}`:''}`;
  m=s.match(/^([a-z][₀-₉0-9′']*)\s+prochází\s+([A-Z]);\s*(.+)$/i);if(m)return `${m[1]}; ${m[2]} ∈ ${m[1]}; ${m[3]}`;
  m=s.match(/^([A-Z](?:[₀-₉0-9′']*)?(?:,\s*[A-Z](?:[₀-₉0-9′']*)?)?)\s*∈\s*(.+)$/);if(m)return `${m[1]}; ${m[1]} ∈ ${m[2]}`;
  m=s.match(/^([A-Z](?:[₀-₉0-9′']*)?)\s*=\s*střed\s+([A-Z]{2})(?:;\s*(.*))?$/);if(m)return `${m[1]}; ${m[1]} = střed ${m[2]}${m[3]?`; ${m[3]}`:''}`;
  m=s.match(/^([A-Z](?:[₀-₉0-9′']*)?)\s*=\s*(.+∩.+)$/);if(m)return `${m[1]}; ${m[1]} ∈ ${m[2]}`;
  m=s.match(/^([A-Z](?:[′'])?)\s+je\s+obraz\s+([A-Z](?:[′'])?)\s+(?:ve středové souměrnosti se středem|podle)\s+([A-Z])$/i);if(m)return `${m[1]}; ${m[3]} = střed ${m[1]}${m[2]}`;
  m=s.match(/^([A-Z](?:[′'])?)\s*=\s*obraz\s+([A-Z](?:[′'])?)\s+ve\s+středové\s+souměrnosti\s+se\s+středem\s+([A-Z])$/i);if(m)return `${m[1]}; ${m[3]} = střed ${m[1]}${m[2]}`;
  m=s.match(/^([a-z])\s+je\s+tečna\s+z\s+([A-Z])\s+ke\s+(.+)$/i);if(m)return `${m[1]}; ${m[2]} ∈ ${m[1]}; ${m[1]} je tečna ke ${m[3]}`;
  m=s.match(/^oblouk\s+([a-z])\s*:\s*(∠.+)$/i);if(m)return `${m[1]}; ${m[1]} = {X; ${m[2]}}`;
  m=s.match(/^([A-Z](?:[′'])?)\s+leží\s+na\s+přímce\s+([A-Z]{2})\s+za\s+bodem\s+([A-Z]);\s*(.+)$/i);if(m)return `${m[1]}; ${m[1]} ∈ ↔${m[2]}; ${m[4]}`;
  return s;
 };
 window.czConstructionForProblem=function(p){
  const sp={
   'b-alpha-va':['AC; |AC| = b','k; k(A; vₐ)','S; S = střed AC','t; t je Thaletova kružnice nad AC','H; H ∈ k ∩ t','p; p = ↔CH','→AB; ∠BAC = α','B; B ∈ →AB ∩ p','△ABC'],
   'b-beta-va':['AC; |AC| = b','k; k(A; vₐ)','S; S = střed AC','t; t je Thaletova kružnice nad AC','H; H ∈ k ∩ t','p; p = ↔CH','q; A ∈ q; ∠(q, p) = β','B; B ∈ p ∩ q','△ABC'],
   'b-alpha-ta':['AC; |AC| = b','→AB; ∠BAC = α','N; N = střed AC','p; N ∈ p; p ∥ AB','k; k(A; tₐ)','M; M ∈ p ∩ k','B; M = střed BC','△ABC'],
   'b-beta-ta':['AC; |AC| = b','l; l = {X; ∠AXC = β}','C′; A = střed CC′','k; k(C′; 2tₐ)','B; B ∈ l ∩ k','△ABC'],
   'b-gamma-ta':['AC; |AC| = b','→CB; ∠ACB = γ','k; k(A; tₐ)','M; M ∈ →CB ∩ k','B; M = střed BC','△ABC'],
   'b-va-ta':['AC; |AC| = b','k₁; k₁(A; vₐ)','S; S = střed AC','t; t je Thaletova kružnice nad AC','H; H ∈ k₁ ∩ t','p; p = ↔CH','k₂; k₂(A; tₐ)','M; M ∈ p ∩ k₂','B; M = střed BC','△ABC'],
   'b-va-tb':['AC; |AC| = b','N; N = střed AC','k₁; k₁(A; vₐ)','S; S = střed AC','t; t je Thaletova kružnice nad AC','H; H ∈ k₁ ∩ t','p; p = ↔CH','k₂; k₂(N; t_b)','B; B ∈ p ∩ k₂','△ABC'],
   'b-va-tc':['AC; |AC| = b','N; N = střed AC','k₁; k₁(A; vₐ)','S; S = střed AC','t; t je Thaletova kružnice nad AC','H; H ∈ k₁ ∩ t','p; p = ↔CH','p′; N ∈ p′; p′ ∥ p','k₂; k₂(C; t_c)','P; P ∈ p′ ∩ k₂','B; P = střed AB','△ABC'],
   '3tez':['CS; |CS| = t_c','T; T ∈ CS; |ST| = t_c/3','T′; T′ ∈ ↔CS; S ∈ TT′; |ST′| = |ST|','k₁; k₁(T; 2t_b/3)','k₂; k₂(T′; 2t_a/3)','B; B ∈ k₁ ∩ k₂','A; S = střed AB','△ABC'],
   'r-angles':['k; k(I; r)','α; α = 180° − β − γ','X, Y, Z; X, Y, Z ∈ k; ∠XIY = 180° − α; ∠YIZ = 180° − γ; ∠ZIX = 180° − β','p; X ∈ p; p ⟂ IX','q; Y ∈ q; q ⟂ IY','s; Z ∈ s; s ⟂ IZ','A; A ∈ p ∩ q','B; B ∈ q ∩ s','C; C ∈ s ∩ p','△ABC'],
   'r-a-beta':['BC; |BC| = a','→BA; ∠ABC = β','o; o je osa úhlu ABC','p; p ∥ BC; d(p, BC) = r','I; I ∈ o ∩ p','k; k(I; r)','t; C ∈ t; t je tečna ke k; t ≠ ↔BC','A; A ∈ t ∩ →BA','△ABC'],
   'bc-va':['A','p; d(A, p) = vₐ','k₁; k₁(A; c)','B; B ∈ k₁ ∩ p','k₂; k₂(A; b)','C; C ∈ k₂ ∩ p; C ≠ B','△ABC'],
   'bc-ta':['AD; |AD| = 2tₐ','k₁; k₁(A; c)','k₂; k₂(D; b)','B; B ∈ k₁ ∩ k₂','M; M = střed AD','C; M = střed BC','△ABC']
  };
  return sp[p.id]||p.construction.map(czConstructionStep);
 };
 window.desktopDetailTemplate=function(p){const cz=czConstructionForProblem(p);return `<div class="grid"><section class="card"><div class="eyebrow">${p.cat}</div><h1>${p.title}</h1><p class="lead">${fmtSegments(p.find)}</p><div class="badges">${p.tags.map(t=>`<span class="badge">${t}</span>`).join('')}</div><dl class="kv"><dt>Zadáno</dt><dd><b>${fmtSegments(p.given)}</b></dd><dt>Úkol</dt><dd>${fmtSegments(p.find)}</dd><dt>Varianty</dt><dd>${fmtSegments(p.variants)}</dd></dl><div class="notice"><b>Podmínka / počet řešení:</b><br>${fmtSegments(p.existence)}</div><div class="construction sketchbox"><h3>Náčrtek situace</h3><div class="sketch-preview">${drawSketch(p)}</div><p><b>Zeleně</b> jsou zadané údaje, <b>černě</b> neznámé části a <b>oranžově</b> pomocné konstrukce.</p><div class="scale-note">Tvar je vykreslen v poměru podle skutečných údajů; mění se jen celkové měřítko.</div></div><button id="solutionToggle" class="solution-toggle">${openSolution?'Skrýt řešení':'Rozbalit kompletní řešení'}</button><div id="solution" class="solution ${openSolution?'open':''}"><div class="steps">${p.steps.map((s,i)=>`<div class="step ${i===stepIndex?'active':''}" data-step="${i}"><span class="num">${i+1}</span><strong>${fmtSegments(s[0])}</strong><p>${fmtSegments(s[1])}</p></div>`).join('')}</div><div class="construction"><h3>Zápis konstrukce</h3><ol>${cz.map(x=>`<li>${x}</li>`).join('')}</ol><div class="construction-note">Zápis je veden běžným českým školním způsobem: nejprve objekt, za středníkem jeho určující vlastnost; nový bod se zapisuje pomocí příslušnosti nebo průsečíku.</div></div></div></section><section class="card diagram-card"><div class="diagram-head"><span class="diagram-title">Grafické řešení krok po kroku</span><span class="step-counter">Krok ${stepIndex+1} z ${p.steps.length}</span></div><div id="svgWrap">${draw(p,stepIndex)}</div><div class="diagram-controls"><button id="prevStep">← Krok zpět</button><button class="primary" id="nextStep">Další krok →</button></div><div class="legend"><span><i class="l-given"></i>zadané</span><span><i class="l-help"></i>pomocné</span><span><i class="l-final"></i>výsledek</span></div></section></div>`};
 window.mobileDetailTemplate=function(p){const cz=czConstructionForProblem(p);const sk=`<div class="mobile-sketch">${drawSketch(p)}</div><p class="mobile-sketch-note"><b>Zeleně</b> známé údaje, <b>černě</b> neznámé části a <b>oranžově</b> pomocné prvky. Tvar odpovídá poměrům v zadání.</p>`;const st=`<div class="mobile-procedure-diagram"><div class="diagram-head"><span class="diagram-title">Grafický krok</span><span class="step-counter">Krok ${stepIndex+1} z ${p.steps.length}</span></div>${draw(p,stepIndex)}<div class="diagram-controls"><button id="mobilePrevStep">← Krok zpět</button><button class="primary" id="mobileNextStep">Další krok →</button></div></div><div class="mobile-steps">${p.steps.map((s,i)=>`<div class="step ${i===stepIndex?'active':''}" data-mobile-step="${i}"><span class="num">${i+1}</span><strong>${fmtSegments(s[0])}</strong><p>${fmtSegments(s[1])}</p></div>`).join('')}</div>`;const co=`<div class="mobile-construction"><ol>${cz.map(x=>`<li>${x}</li>`).join('')}</ol></div>`;return `<div class="mobile-detail-wrap"><article class="mobile-detail-card"><div class="eyebrow">${p.cat}</div><h1>${p.title}</h1><p class="lead">${fmtSegments(p.find)}</p><div class="badges">${p.tags.map(t=>`<span class="badge">${t}</span>`).join('')}</div><div class="mobile-assignment"><div class="mobile-assignment-row"><span>Zadáno</span><b>${fmtSegments(p.given)}</b></div><div class="mobile-assignment-row"><span>Úkol</span><div>${fmtSegments(p.find)}</div></div><div class="mobile-assignment-row"><span>Varianty</span><div>${fmtSegments(p.variants)}</div></div></div><div class="notice"><b>Podmínka / počet řešení:</b><br>${fmtSegments(p.existence)}</div><div class="mobile-accordions">${mobileAccordion('sketch','△','Náčrtek',sk)}${mobileAccordion('steps','1→','Konstrukce krok po kroku',st)}${mobileAccordion('construction','✎','Zápis konstrukce',co)}</div></article></div>`};
 if(typeof renderAll==='function')renderAll();
})();
